### ISSUE TITLE
Support Robot Framework 3.2

### ISSUE THREAD

**Issue by sergii-tsymbal-exa** [guykisel/pre-commit-robotframework-tidy#4]
I am getting this error when using this hook with robotframework 3.2
```
robotframework tidy wrapper..............................................Failed
- hook id: robotframework-tidy-wrapper
- exit code: 1

Traceback (most recent call last):
  File "/Users/sergiitsymbal/.cache/pre-commit/repoyh0pnzox/py_env-python3.7/bin/python-robotframework-tidy", line 8, in <module>
    sys.exit(main())
  File "/Users/sergiitsymbal/.cache/pre-commit/repoyh0pnzox/py_env-python3.7/lib/python3.7/site-packages/pre_commit_robotframework_tidy/rf_tidy.py", line 20, in main
    format='robot')
TypeError: __init__() got an unexpected keyword argument 'format'
```

Tidy API changed and it does not accept `format` argument
If I remove `format='robot'` in `rf_tidy.py`, the hook works fine

It should probably be enough to just remove that line, because robotframework version is not pinned and the last version will always be downloaded

**Comment by guykisel** [comment]
that sounds good, want to submit a PR? :)
